target 'ppoggle' do
    # IMPORTANT: Make sure use_frameworks! is included at the top of the file
    use_frameworks!

    pod 'UICircularProgressRing'
    pod 'Alamofire'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
   end