platform :ios, '12.1'
target 'ppoggle' do
    # IMPORTANT: Make sure use_frameworks! is included at the top of the file

    pod 'UICircularProgressRing'
    pod 'Alamofire', '~> 5.0.0-beta.3'
	pod 'SwiftLint'
	pod 'Then', '2.6.0'
	pod 'SnapKit', '4.2.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
   end
